n, m = map(int, input().split())
a = list(map(int, input().split()))
b = list(map(int, input().split()))
a = list(set(a))
b = list(set(b))
a.sort()
b.sort()
a = "".join(map(str, a))
b = "".join(map(str, b))
print("YES" if a == b else "NO")